---
title: "Class_07"
author: "Carter Palmer"
date: "October 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Revisit our functions from last time

```{r}
source("http://tinyurl.com/rescale-R")
```

Trying rescale() function from last day

```{r}
rescale(1:10)
```

```{r}
rescale2( c(3, 10, 4, "barry", 4))
```

Write a function both_na()

```{r}
#from stack overflow
x <- c(1, 2, NA, 3, NA)
y <- c(NA, 3, NA, 3, 4)

which(is.na(x))
which(is.na(y))

```
```{r}
both_na <-  function(x,y){
  sum(is.na(x)&is.na(y))
}
both_na(x,y)
```
```{r}
both_na2 <- function(x, y) {
  if (length(x) != length(y))
  stop("You're stupid Carter")
  (sum(is.na(x)&is.na(y)))
  
}
```

```{r}
z <-  c(NA, 3, 4)
both_na2(x, z)
```

```{r}
stu1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
stu2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
```

```{r}
grade <- function(x){
  y <-  length(x)
  grades_ordered <- sort(x, na.last = FALSE)
  top_grades <- grades_ordered[2:y]
  mean(top_grades)
}
  
grade(stu1)
grade(stu2)
```

```{r}
source("https://tinyurl.com/gradeinput")
```

```{r}
student_grades <- read.csv("https://tinyurl.com/gradeinput")
```

```{r}
grade2 <- function(x){
  for (i in 1:nrow(x))
  gradesvec = x[i, 2:6]
  y <-  length(gradesvec)
  grades_ordered <- sort(gradesvec, na.last = FALSE)
  top_grades <- grades_ordered[2:y]
  print(mean(top_grades))
  print(x[i,1])
}
```


```{r}
grade2(student_grades)
```

```{r}
install.packages("devtools")
``'

